### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by BenM4k**
Setup linters and the rails application

### CODE REVIEW

**Comment by hmunish** [comment]
@BenM4k, please setup the project on the newly created branch. And not on the main branch. We are not allowed to commit on main or dev branch directly.

**Comment by hmunish** [comment]
@BenM4k , I think you can rename the main branch to some other name. And create a new main branch. As that would be convenient to do.

**Review by hmunish — COMMENTED** [review]
Please refer to the comments.

**Comment by BenM4k** [comment]
@hmunish 😅😅It's okay. I created a new branch then I forgot to check it out before creating the app

**Comment by hmunish** [comment]
@BenM4k , I will update the branch names.

**Pull request closed without merging**
